# Generated by Django 2.2.5 on 2019-10-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_texto', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField(verbose_name='fecha_de_publicacion')),
            ],
        ),
    ]
